//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindyCircle
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attendance()
        {
            this.PunchCardUsages = new HashSet<PunchCardUsage>();
        }
    
        public int AttendanceID { get; set; }
        public int MemberID { get; set; }
        public int PracticeID { get; set; }
        public int PaymentType { get; set; }
        public string PaymentTypeText
        {
            get
            {
                switch (PaymentType)
                {
                    case 0: return "None";
                    case 1: return "Cash";
                    case 2: return "Punch card";
                    default: return "Other";
                }
            }
        }
        public decimal PaymentAmount { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Practice Practice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PunchCardUsage> PunchCardUsages { get; set; }
    }
}
