//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindyCircle
{
    using System.Collections.Generic;
    using System.Linq;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Attendances = new HashSet<Attendance>();
            this.PunchCardsHeld = new HashSet<PunchCard>();
            this.PunchCardsPurchased = new HashSet<PunchCard>();
        }
    
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool Inactive { get; set; }
        public string FirstLastName { get { return FirstName + " " + LastName; } }
        public string LastFirstName { get { return LastName + ", " + FirstName; } }
        public int RemainingPunches
        {
            get { return PunchCardsHeld.Sum(t => t.RemainingPunches); }
        }
        public decimal TotalPaid
        {
            get { return Attendances.Sum(t => t.PaymentAmount) + PunchCardsPurchased.Sum(t => t.PurchaseAmount); }
        }
        public int TotalAttendance
        {
            get { return Attendances.Count; }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PunchCard> PunchCardsHeld { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PunchCard> PunchCardsPurchased { get; set; }
    }
}
