//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindyCircle
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunchCardUsage
    {
        public int UsageID { get; set; }
        public int AttendanceID { get; set; }
        public int PunchCardID { get; set; }
    
        public virtual Attendance Attendance { get; set; }
        public virtual PunchCard PunchCard { get; set; }
    }
}
