//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LindyCircle
{
    using System;
    using System.Collections.Generic;

    public partial class PunchCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PunchCard()
        {
            this.PunchCardUsages = new HashSet<PunchCardUsage>();
        }

        public int PunchCardID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal PurchaseAmount { get; set; }
        public int PurchaseMemberID { get; set; }
        public int CurrentMemberID { get; set; }
        public int RemainingPunches { get { return 5 - PunchCardUsages.Count; } }

        public virtual Member CurrentMember { get; set; }
        public virtual Member PurchaseMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PunchCardUsage> PunchCardUsages { get; set; }
    }
}
